// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/classroom_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClassroomServiceClient is the client API for ClassroomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassroomServiceClient interface {
	CreateClassroom(ctx context.Context, in *CreateClassroomRequest, opts ...grpc.CallOption) (*ClassroomResponse, error)
	GetClassroomById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ClassroomResponse, error)
	GetClassroomByName(ctx context.Context, in *Name, opts ...grpc.CallOption) (*ClassroomResponse, error)
	UpdateClassroom(ctx context.Context, in *UpdateClassroomRequest, opts ...grpc.CallOption) (*ClassroomResponse, error)
	DeleteClassroom(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Id, error)
	JoinClass(ctx context.Context, in *Id, opts ...grpc.CallOption) (*StudentClassResponse, error)
	AddStudent(ctx context.Context, in *AddStudentRequest, opts ...grpc.CallOption) (*StudentClassResponse, error)
	DeleteStudentInClass(ctx context.Context, in *DeleteStudentInClassRequest, opts ...grpc.CallOption) (*StudentClassResponse, error)
	Students(ctx context.Context, in *Id, opts ...grpc.CallOption) (*StudentsResponse, error)
	JoinRequest(ctx context.Context, in *Id, opts ...grpc.CallOption) (*JoinClassRequestsResponse, error)
	UpdateJoinRequest(ctx context.Context, in *Id, opts ...grpc.CallOption) (*StudentClassResponse, error)
	DeleteJoinRequest(ctx context.Context, in *Id, opts ...grpc.CallOption) (*StudentClassResponse, error)
}

type classroomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClassroomServiceClient(cc grpc.ClientConnInterface) ClassroomServiceClient {
	return &classroomServiceClient{cc}
}

func (c *classroomServiceClient) CreateClassroom(ctx context.Context, in *CreateClassroomRequest, opts ...grpc.CallOption) (*ClassroomResponse, error) {
	out := new(ClassroomResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/CreateClassroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) GetClassroomById(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ClassroomResponse, error) {
	out := new(ClassroomResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/GetClassroomById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) GetClassroomByName(ctx context.Context, in *Name, opts ...grpc.CallOption) (*ClassroomResponse, error) {
	out := new(ClassroomResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/GetClassroomByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) UpdateClassroom(ctx context.Context, in *UpdateClassroomRequest, opts ...grpc.CallOption) (*ClassroomResponse, error) {
	out := new(ClassroomResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/UpdateClassroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) DeleteClassroom(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/DeleteClassroom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) JoinClass(ctx context.Context, in *Id, opts ...grpc.CallOption) (*StudentClassResponse, error) {
	out := new(StudentClassResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/JoinClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) AddStudent(ctx context.Context, in *AddStudentRequest, opts ...grpc.CallOption) (*StudentClassResponse, error) {
	out := new(StudentClassResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/AddStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) DeleteStudentInClass(ctx context.Context, in *DeleteStudentInClassRequest, opts ...grpc.CallOption) (*StudentClassResponse, error) {
	out := new(StudentClassResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/DeleteStudentInClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) Students(ctx context.Context, in *Id, opts ...grpc.CallOption) (*StudentsResponse, error) {
	out := new(StudentsResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/Students", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) JoinRequest(ctx context.Context, in *Id, opts ...grpc.CallOption) (*JoinClassRequestsResponse, error) {
	out := new(JoinClassRequestsResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/JoinRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) UpdateJoinRequest(ctx context.Context, in *Id, opts ...grpc.CallOption) (*StudentClassResponse, error) {
	out := new(StudentClassResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/UpdateJoinRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classroomServiceClient) DeleteJoinRequest(ctx context.Context, in *Id, opts ...grpc.CallOption) (*StudentClassResponse, error) {
	out := new(StudentClassResponse)
	err := c.cc.Invoke(ctx, "/Classroom.ClassroomService/DeleteJoinRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassroomServiceServer is the server API for ClassroomService service.
// All implementations must embed UnimplementedClassroomServiceServer
// for forward compatibility
type ClassroomServiceServer interface {
	CreateClassroom(context.Context, *CreateClassroomRequest) (*ClassroomResponse, error)
	GetClassroomById(context.Context, *Id) (*ClassroomResponse, error)
	GetClassroomByName(context.Context, *Name) (*ClassroomResponse, error)
	UpdateClassroom(context.Context, *UpdateClassroomRequest) (*ClassroomResponse, error)
	DeleteClassroom(context.Context, *Id) (*Id, error)
	JoinClass(context.Context, *Id) (*StudentClassResponse, error)
	AddStudent(context.Context, *AddStudentRequest) (*StudentClassResponse, error)
	DeleteStudentInClass(context.Context, *DeleteStudentInClassRequest) (*StudentClassResponse, error)
	Students(context.Context, *Id) (*StudentsResponse, error)
	JoinRequest(context.Context, *Id) (*JoinClassRequestsResponse, error)
	UpdateJoinRequest(context.Context, *Id) (*StudentClassResponse, error)
	DeleteJoinRequest(context.Context, *Id) (*StudentClassResponse, error)
	mustEmbedUnimplementedClassroomServiceServer()
}

// UnimplementedClassroomServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClassroomServiceServer struct {
}

func (UnimplementedClassroomServiceServer) CreateClassroom(context.Context, *CreateClassroomRequest) (*ClassroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) GetClassroomById(context.Context, *Id) (*ClassroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClassroomById not implemented")
}
func (UnimplementedClassroomServiceServer) GetClassroomByName(context.Context, *Name) (*ClassroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClassroomByName not implemented")
}
func (UnimplementedClassroomServiceServer) UpdateClassroom(context.Context, *UpdateClassroomRequest) (*ClassroomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) DeleteClassroom(context.Context, *Id) (*Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClassroom not implemented")
}
func (UnimplementedClassroomServiceServer) JoinClass(context.Context, *Id) (*StudentClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinClass not implemented")
}
func (UnimplementedClassroomServiceServer) AddStudent(context.Context, *AddStudentRequest) (*StudentClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStudent not implemented")
}
func (UnimplementedClassroomServiceServer) DeleteStudentInClass(context.Context, *DeleteStudentInClassRequest) (*StudentClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStudentInClass not implemented")
}
func (UnimplementedClassroomServiceServer) Students(context.Context, *Id) (*StudentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Students not implemented")
}
func (UnimplementedClassroomServiceServer) JoinRequest(context.Context, *Id) (*JoinClassRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRequest not implemented")
}
func (UnimplementedClassroomServiceServer) UpdateJoinRequest(context.Context, *Id) (*StudentClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJoinRequest not implemented")
}
func (UnimplementedClassroomServiceServer) DeleteJoinRequest(context.Context, *Id) (*StudentClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJoinRequest not implemented")
}
func (UnimplementedClassroomServiceServer) mustEmbedUnimplementedClassroomServiceServer() {}

// UnsafeClassroomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassroomServiceServer will
// result in compilation errors.
type UnsafeClassroomServiceServer interface {
	mustEmbedUnimplementedClassroomServiceServer()
}

func RegisterClassroomServiceServer(s grpc.ServiceRegistrar, srv ClassroomServiceServer) {
	s.RegisterService(&ClassroomService_ServiceDesc, srv)
}

func _ClassroomService_CreateClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).CreateClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/CreateClassroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).CreateClassroom(ctx, req.(*CreateClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_GetClassroomById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).GetClassroomById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/GetClassroomById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).GetClassroomById(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_GetClassroomByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).GetClassroomByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/GetClassroomByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).GetClassroomByName(ctx, req.(*Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_UpdateClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClassroomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).UpdateClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/UpdateClassroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).UpdateClassroom(ctx, req.(*UpdateClassroomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_DeleteClassroom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).DeleteClassroom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/DeleteClassroom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).DeleteClassroom(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_JoinClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).JoinClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/JoinClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).JoinClass(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_AddStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).AddStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/AddStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).AddStudent(ctx, req.(*AddStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_DeleteStudentInClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStudentInClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).DeleteStudentInClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/DeleteStudentInClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).DeleteStudentInClass(ctx, req.(*DeleteStudentInClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_Students_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).Students(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/Students",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).Students(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_JoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).JoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/JoinRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).JoinRequest(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_UpdateJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).UpdateJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/UpdateJoinRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).UpdateJoinRequest(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClassroomService_DeleteJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassroomServiceServer).DeleteJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Classroom.ClassroomService/DeleteJoinRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassroomServiceServer).DeleteJoinRequest(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassroomService_ServiceDesc is the grpc.ServiceDesc for ClassroomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassroomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Classroom.ClassroomService",
	HandlerType: (*ClassroomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClassroom",
			Handler:    _ClassroomService_CreateClassroom_Handler,
		},
		{
			MethodName: "GetClassroomById",
			Handler:    _ClassroomService_GetClassroomById_Handler,
		},
		{
			MethodName: "GetClassroomByName",
			Handler:    _ClassroomService_GetClassroomByName_Handler,
		},
		{
			MethodName: "UpdateClassroom",
			Handler:    _ClassroomService_UpdateClassroom_Handler,
		},
		{
			MethodName: "DeleteClassroom",
			Handler:    _ClassroomService_DeleteClassroom_Handler,
		},
		{
			MethodName: "JoinClass",
			Handler:    _ClassroomService_JoinClass_Handler,
		},
		{
			MethodName: "AddStudent",
			Handler:    _ClassroomService_AddStudent_Handler,
		},
		{
			MethodName: "DeleteStudentInClass",
			Handler:    _ClassroomService_DeleteStudentInClass_Handler,
		},
		{
			MethodName: "Students",
			Handler:    _ClassroomService_Students_Handler,
		},
		{
			MethodName: "JoinRequest",
			Handler:    _ClassroomService_JoinRequest_Handler,
		},
		{
			MethodName: "UpdateJoinRequest",
			Handler:    _ClassroomService_UpdateJoinRequest_Handler,
		},
		{
			MethodName: "DeleteJoinRequest",
			Handler:    _ClassroomService_DeleteJoinRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/classroom_service.proto",
}
